# Generated by Django 4.0.6 on 2022-08-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cariculam_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CariculamTopicRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_topic_rate_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam Topic Rates',
                'db_table': 'jinoe_user_cariculam_topic_rates',
            },
        ),
        migrations.CreateModel(
            name='CariculamTopicLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('like', models.BooleanField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_topic_like_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam Topic Likes',
                'db_table': 'jinoe_user_cariculam_topic_likes',
            },
        ),
        migrations.CreateModel(
            name='CariculamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_qn_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamtopics')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Questions',
                'db_table': 'jinoe_cariculam_topic_questions',
            },
        ),
        migrations.CreateModel(
            name='CariculamAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('answer', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_ans_opt_created_by', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_answer_options_question', to='cariculam_interactive.cariculamquestions')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Question Answers',
                'db_table': 'jinoe_cariculam_question_answers',
            },
        ),
        migrations.CreateModel(
            name='CariculamAnswerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('answer_log', models.CharField(blank=True, max_length=60, null=True)),
                ('scores', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_ans_log_created_by', to=settings.AUTH_USER_MODEL)),
                ('questin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_interactive.cariculamquestions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam Answer Logs',
                'db_table': 'jinoe_user_cariculam_answer_logs',
            },
        ),
    ]
