# Generated by Django 4.0.6 on 2022-07-10 05:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_subjects_progress_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Subject topics'},
        ),
        migrations.AddField(
            model_name='topics',
            name='create_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topics',
            name='media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_status',
            field=models.CharField(choices=[('ST', 'STARTED'), ('NST', 'NOT_STARTED'), ('DL', 'DELAYED'), ('CMP', 'COMPLETED'), ('DISC', 'DISQUALIFIED')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='topics',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='progress_status',
            field=models.CharField(choices=[('ST', 'STARTED'), ('NST', 'NOT_STARTED'), ('DL', 'DELAYED'), ('CMP', 'COMPLETED'), ('DISC', 'DISQUALIFIED')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AlterModelTable(
            name='topics',
            table='jinoe_subject_topics',
        ),
        migrations.CreateModel(
            name='SubTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_topic_status', models.CharField(choices=[('ST', 'STARTED'), ('NST', 'NOT_STARTED'), ('DL', 'DELAYED'), ('CMP', 'COMPLETED'), ('DISC', 'DISQUALIFIED')], default='NOT_STARTED', max_length=30)),
                ('media', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topics')),
            ],
            options={
                'verbose_name_plural': 'Topic subtopics',
                'db_table': 'jinoe_topic_subtopics',
            },
        ),
    ]
