# Generated by Django 4.0.6 on 2022-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_topics_options_topics_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopics',
            options={'verbose_name_plural': 'Topic Subtopics'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Subject Topics'},
        ),
        migrations.AlterField(
            model_name='subjects',
            name='progress_status',
            field=models.CharField(choices=[('ST', 'STARTED'), ('NST', 'NOT_STARTED'), ('DL', 'DELAYED'), ('CMP', 'COMPLETED'), ('DISC', 'DISQUALIFIED')], max_length=30),
        ),
    ]
