# Generated by Django 4.0.6 on 2022-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subtopics_options_alter_topics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name_plural': 'Eduction Levels'},
        ),
        migrations.AddField(
            model_name='levels',
            name='order_by',
            field=models.IntegerField(null=True),
        ),
    ]
