# Generated by Django 4.0.6 on 2022-07-17 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_levels_options_levels_order_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, null=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_to_set', to='core.levels')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student_set', to='core.levels')),
            ],
            options={
                'verbose_name_plural': 'Enrolled Education level',
                'db_table': 'jinoe_enrolled_eduction_level',
            },
        ),
    ]
