# Generated by Django 4.0.6 on 2022-07-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_enrollment_level_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.levels'),
        ),
    ]
