# Generated by Django 4.0.6 on 2022-07-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_enrollment_level_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrol_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='progress_status',
            field=models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='sub_topic_status',
            field=models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_status',
            field=models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30),
        ),
        migrations.AlterField(
            model_name='topics',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
