# Generated by Django 4.0.6 on 2022-07-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_modules_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_set', to='core.levels'),
        ),
    ]
