# Generated by Django 4.0.6 on 2022-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_modules_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='module_type',
            field=models.CharField(choices=[('normal', 'normal module'), ('core', 'core module')], max_length=200, null=True),
        ),
    ]
