# Generated by Django 4.0.6 on 2022-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modules_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='order_by',
            field=models.IntegerField(null=True),
        ),
    ]
