# Generated by Django 4.0.6 on 2022-07-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_modules_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
