# Generated by Django 4.0.6 on 2022-07-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enrollment_create_by_alter_enrollment_create_at_and_more'),
        ('core', '0015_modules_description'),
    ]

    operations = [
    ]
