# Generated by Django 4.0.6 on 2022-07-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_modules_level_sublevelset_sublevelentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublevelset',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='sublevelset',
            name='sub_level_set_level_id',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='module_sub_level_entry_id',
        ),
        migrations.AddField(
            model_name='modules',
            name='Level_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='module_set', to='core.levels'),
        ),
        migrations.DeleteModel(
            name='SubLevelEntry',
        ),
        migrations.DeleteModel(
            name='SubLevelSet',
        ),
    ]
