# Generated by Django 4.0.6 on 2022-07-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_modules_level_sublevelset_sublevelentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sublevelentry',
            options={'verbose_name_plural': 'Eduction Sub Level Entry'},
        ),
    ]
