# Generated by Django 4.0.6 on 2022-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sublevelset_create_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='Level_id',
            new_name='Level',
        ),
    ]
