# Generated by Django 4.0.6 on 2022-07-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sublevelset_create_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='Level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='module_set', to='core.levels'),
        ),
    ]
