# Generated by Django 4.0.6 on 2022-07-28 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_rename_level_id_modules_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='Level',
            new_name='module_Level_id',
        ),
        migrations.RenameField(
            model_name='subtopics',
            old_name='media',
            new_name='sub_tipic_media',
        ),
        migrations.RenameField(
            model_name='subtopics',
            old_name='name',
            new_name='sub_topic_name',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='module',
        ),
        migrations.RemoveField(
            model_name='subtopics',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_module_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subject_module_id_col', to='core.modules'),
        ),
        migrations.AddField(
            model_name='subtopics',
            name='sub_tipic_topic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tipic_topic_id_col', to='core.topics'),
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_subject_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='topic_subject_id_col', to='core.subjects'),
        ),
        migrations.CreateModel(
            name='SubSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('sub_sub_topic_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_sub_topic_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30)),
                ('sub_sub_topic_media', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_sub_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_topic_id_col', to='core.subtopics')),
            ],
            options={
                'verbose_name_plural': 'Topic Sub Subtopics',
                'db_table': 'jinoe_topic_sub_subtopics',
            },
        ),
    ]
