# Generated by Django 4.0.6 on 2022-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_topics_topic_subject_id_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='sub_tipic_media',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topics',
            name='media',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
