# Generated by Django 4.0.6 on 2022-07-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_alter_subtopics_sub_tipic_media_alter_topics_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubtopic',
            name='sub_sub_topic_media',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_video_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_topic_id_col', to='core.topics')),
            ],
            options={
                'verbose_name_plural': 'Topic Videos',
                'db_table': 'jinoe_topic_videos',
            },
        ),
        migrations.CreateModel(
            name='SubTopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_sub_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_topic_id_col', to='core.subtopics')),
            ],
            options={
                'verbose_name_plural': 'Topic Subtopic Videos',
                'db_table': 'jinoe_topic_subtopic_videos',
            },
        ),
        migrations.CreateModel(
            name='SubSubTopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_sub_sub_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sub_sub_topic_id_col', to='core.subsubtopic')),
            ],
            options={
                'verbose_name_plural': 'Topic Sub Subtopic Videos',
                'db_table': 'jinoe_topic_sub_subtopic_videos',
            },
        ),
    ]
