# Generated by Django 4.0.6 on 2022-07-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_subsubtopic_sub_sub_topic_media_topicvideos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Module Topics'},
        ),
    ]
