# Generated by Django 4.0.6 on 2022-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_topiclikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlogs',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='answerlogs',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topiclikes',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topiclikes',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topicrates',
            name='create_at',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topicrates',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
