# Generated by Django 4.0.6 on 2022-08-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cariculam_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CariculamSubTopicRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_sub_topic_rate_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamsubtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam SubTopic Rates',
                'db_table': 'jinoe_user_cariculam_sub_topic_rates',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopicQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_qn_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamsubtopics')),
            ],
            options={
                'verbose_name_plural': 'Cariculam SubTopic Questions',
                'db_table': 'jinoe_cariculam_sub_topic_questions',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopicLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_sub_topic_like_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_core.cariculamsubtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam SubTopic Likes',
                'db_table': 'jinoe_user_cariculam_sub_topic_likes',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopicAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_ans_opt_created_by', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_c_answer_options_question', to='cariculam_sub_topic_interactive.cariculamsubtopicquestions')),
            ],
            options={
                'verbose_name_plural': 'Cariculam SubTopic Question Answers',
                'db_table': 'jinoe_cariculam_sub_topic_question_answers',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopicAnswerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_log', models.CharField(blank=True, max_length=60)),
                ('scores', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_ans_log_created_by', to=settings.AUTH_USER_MODEL)),
                ('questin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariculam_sub_topic_interactive.cariculamsubtopicquestions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Cariculam SubTopic Answer Logs',
                'db_table': 'jinoe_user_cariculam_subtopic_answer_logs',
            },
        ),
    ]
