# Generated by Django 4.0.6 on 2022-07-12 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_standards', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_evls_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Performance Evaluations',
                'db_table': 'jinoe_performance_evaluations',
            },
        ),
        migrations.CreateModel(
            name='ReputationQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_quality', models.TextField(blank=True)),
                ('student_score', models.IntegerField(default=0)),
                ('supervisor_score', models.IntegerField(default=0)),
                ('agreed_score', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_rp_qlt_created_by', to=settings.AUTH_USER_MODEL)),
                ('reputation_quality_evaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_management.performanceevaluation')),
            ],
            options={
                'verbose_name_plural': 'Performance Reputation Quality',
                'db_table': 'jinoe_performance_reputation_quality',
            },
        ),
        migrations.CreateModel(
            name='PerformanceObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(blank=True, null=True)),
                ('required_resources', models.BooleanField()),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('objective_score', models.IntegerField(default=0)),
                ('objective_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('AGR', 'Agreed'), ('DSAG', 'Disagreed')], default='NST', max_length=30)),
                ('evaluation_status', models.CharField(choices=[('ASD', 'Assessed'), ('UASD', 'Unassessed')], default='UASD', max_length=30)),
                ('objective_goals', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_obj_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Performance Objectives',
                'db_table': 'jinoe_performance_objectives',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_obj_resrc_created_by', to=settings.AUTH_USER_MODEL)),
                ('resources_objective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_management.performanceobjectives')),
            ],
            options={
                'verbose_name_plural': 'Performance Objective Resources',
                'db_table': 'jinoe_performance_objective_resources',
            },
        ),
    ]
