# Generated by Django 4.0.6 on 2022-08-04 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0026_alter_topics_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CariculamChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('chat_room_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_c_chat_room_topic_id_col', to='core.topics')),
                ('chat_room_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_c_chat_room_user_id_col', to=settings.AUTH_USER_MODEL)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_chat_room_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cariculam Chat Room',
                'db_table': 'jinoe_cariculam_chat_room',
            },
        ),
        migrations.CreateModel(
            name='CariculamChatRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_c_message_chat_room_created_by', to=settings.AUTH_USER_MODEL)),
                ('message_chat_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_c_message_chat_room_id_col', to='cariculam_chatroom.cariculamchatroom')),
                ('message_chat_room_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_c_message_chat_room_user_id_col', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cariculam Chat Room Messages',
                'db_table': 'jinoe_cariculam_chat_room_messages',
            },
        ),
    ]
