# Generated by Django 4.0.6 on 2022-07-13 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=300)),
                ('main_body', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, db_column='data')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disc_created_by', to=settings.AUTH_USER_MODEL)),
                ('discussion_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_user_id_col', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discussions',
                'db_table': 'jinoe_discussions',
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disc_reply_created_by', to=settings.AUTH_USER_MODEL)),
                ('reply_discussion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_discussion_id_col', to='forums.discussion')),
                ('reply_discussion_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_discussion_user_id_col', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discussions Replies',
                'db_table': 'jinoe_discussions_replies',
            },
        ),
        migrations.CreateModel(
            name='DiscussionLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disc_likes_created_by', to=settings.AUTH_USER_MODEL)),
                ('likes_discussion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_discussion_id_col', to='forums.discussion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discussions Likes',
                'db_table': 'jinoe_discussions_likes',
            },
        ),
    ]
