# Generated by Django 4.0.6 on 2022-07-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_topic_interactive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopicansweroptions',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='subtopicansweroptions',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='subtopiclikes',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='subtopiclikes',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='subtopiclikes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subtopicquestions',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='subtopicquestions',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='subtopicrates',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='subtopicrates',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='subtopicrates',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='SubTopicAnswerLogs',
        ),
        migrations.DeleteModel(
            name='SubTopicAnswerOptions',
        ),
        migrations.DeleteModel(
            name='SubTopicLikes',
        ),
        migrations.DeleteModel(
            name='SubTopicQuestions',
        ),
        migrations.DeleteModel(
            name='SubTopicRates',
        ),
    ]
