# Generated by Django 4.0.6 on 2022-07-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_subtopics_options_alter_topics_options_and_more'),
        ('sub_topic_interactive', '0002_remove_subtopicansweroptions_create_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopicRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topic_rate_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User SubTopic Rates',
                'db_table': 'jinoe_user_sub_topic_rates',
            },
        ),
        migrations.CreateModel(
            name='SubTopicQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_qn_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopics')),
            ],
            options={
                'verbose_name_plural': 'SubTopic Questions',
                'db_table': 'jinoe_sub_topic_questions',
            },
        ),
        migrations.CreateModel(
            name='SubTopicLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topic_like_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User SubTopic Likes',
                'db_table': 'jinoe_user_sub_topic_likes',
            },
        ),
        migrations.CreateModel(
            name='SubTopicAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_ans_opt_created_by', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options_question', to='sub_topic_interactive.subtopicquestions')),
            ],
            options={
                'verbose_name_plural': 'SubTopic Question Answers',
                'db_table': 'jinoe_sub_topic_question_answers',
            },
        ),
        migrations.CreateModel(
            name='SubTopicAnswerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_log', models.CharField(blank=True, max_length=60)),
                ('scores', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_ans_log_created_by', to=settings.AUTH_USER_MODEL)),
                ('questin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_topic_interactive.subtopicquestions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User SubTopic Answer Logs',
                'db_table': 'jinoe_user_sub_topic_answer_logs',
            },
        ),
    ]
