# Generated by Django 4.0.6 on 2022-07-11 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_subtopics_options_alter_topics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, null=True)),
                ('endTime', models.DateTimeField(auto_created=True, null=True)),
                ('startTime', models.DateTimeField(auto_created=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_created_by', to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subject Schedules',
                'db_table': 'jinoe_subject_schedules',
            },
        ),
    ]
