# Generated by Django 4.0.6 on 2022-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedules',
            name='status',
            field=models.CharField(choices=[('NST', 'Not_Started'), ('DL', 'Delayed'), ('CMP', 'Completed'), ('PS', 'Postponed')], default='NST', max_length=30),
        ),
    ]
