# Generated by Django 4.0.6 on 2022-07-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sublevelentry_sublevelset_remove_subjects_create_by_and_more'),
        ('schedules', '0004_alter_subjectschedules_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectschedules',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modules'),
        ),
    ]
