# Generated by Django 4.0.6 on 2022-08-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_skills_experience_educationbacbackground_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CariculamLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('order_by', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clv_created_by', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Levels',
                'db_table': 'jinoe_cariculam_user_Levels',
            },
        ),
        migrations.CreateModel(
            name='CariculamModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('module_type', models.CharField(choices=[('normal', 'normal module'), ('core', 'core module')], max_length=200, null=True)),
                ('progress_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('order_by', models.IntegerField(null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_md_created_by', to=settings.AUTH_USER_MODEL)),
                ('module_Level_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='c_module_set', to='cariculam_core.cariculamlevels')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Level Modules',
                'db_table': 'jinoe_cariculam_level_modules',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_sbj_created_by', to=settings.AUTH_USER_MODEL)),
                ('module_subject_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='c_module_subject_id_col', to='cariculam_core.cariculammodules')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Module Subjects',
                'db_table': 'jinoe_cariculam_module_subjects',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('sub_sub_topic_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_sub_topic_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30)),
                ('sub_sub_topic_media', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Sub Subtopics',
                'db_table': 'jinoe_cariculam_topic_sub_subtopics',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('sub_topic_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_topic_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30)),
                ('sub_tipic_media', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Subtopics',
                'db_table': 'jinoe_cariculam_topic_subtopics',
            },
        ),
        migrations.CreateModel(
            name='CariculamTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('topic_status', models.CharField(choices=[('NST', 'Not_Started'), ('ST', 'Started'), ('DL', 'Delayed'), ('CMP', 'Completed')], default='NST', max_length=30)),
                ('media', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('topic_subject_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='c_topic_subject_id_col', to='cariculam_core.cariculamsubjects')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Module Topics',
                'db_table': 'jinoe_cariculam_subject_topics',
            },
        ),
        migrations.CreateModel(
            name='CariculamTopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_topic_video_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_video_topic_id_col', to='cariculam_core.cariculamtopics')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Videos',
                'db_table': 'jinoe_cariculam_topic_videos',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubTopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_video_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_sub_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_video_sub_topic_id_col', to='cariculam_core.cariculamsubtopics')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Subtopic Videos',
                'db_table': 'jinoe_cariculam_topic_subtopic_videos',
            },
        ),
        migrations.AddField(
            model_name='cariculamsubtopics',
            name='sub_tipic_topic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_tipic_topic_id_col', to='cariculam_core.cariculamtopics'),
        ),
        migrations.CreateModel(
            name='CariculamSubSubTopicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_topic_video_media', models.FileField(blank=True, max_length=200, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_video_sub_sub_topic_created_by', to=settings.AUTH_USER_MODEL)),
                ('video_sub_sub_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_video_sub_sub_topic_id_col', to='cariculam_core.cariculamsubsubtopic')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Topic Sub Subtopic Videos',
                'db_table': 'jinoe_cariculam_topic_sub_subtopic_videos',
            },
        ),
        migrations.AddField(
            model_name='cariculamsubsubtopic',
            name='sub_sub_topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_sub_topic_id_col', to='cariculam_core.cariculamsubtopics'),
        ),
        migrations.CreateModel(
            name='CariculamSubLevelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_stlv_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_level_set_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_level_set_level_id_col', to='cariculam_core.cariculamlevels')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Sub Level Sets',
                'db_table': 'jinoe_cariculam_sub_level_set',
            },
        ),
        migrations.CreateModel(
            name='CariculamSubLevelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_stlv_entry_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_level_entry_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_sub_level_entry_set_id_col', to='cariculam_core.cariculamsublevelset')),
            ],
            options={
                'verbose_name_plural': 'Cariculam Sub Level Set Elements',
                'db_table': 'jinoe_cariculam_sub_level_set_elements',
            },
        ),
        migrations.CreateModel(
            name='CariculamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, editable=False, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_enrol_created_by', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_enrolled_to_set', to='cariculam_core.cariculamlevels')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_enrolled_student_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enrolled Cariculam level',
                'db_table': 'jinoe_enrolled_cariculam_eduction_level',
            },
        ),
    ]
