# Generated by Django 4.0.6 on 2022-08-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cariculam_core', '0003_alter_cariculamsubjects_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cariculamsubjects',
            name='module_subject_id',
        ),
    ]
