# Generated by Django 4.0.6 on 2022-07-18 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinerUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, db_column='data')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('event_date', models.DateField(default=datetime.datetime.now)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wbn_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Webiner Updated',
                'db_table': 'jinoe_webiner_updated',
            },
        ),
        migrations.CreateModel(
            name='WebinerPioneers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.TextField(blank=True, db_column='data')),
                ('short_description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wbn_pnr_created_by', to=settings.AUTH_USER_MODEL)),
                ('pioneers_webiner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pioneers_webiner_id_col', to='webinar.webinerupdates')),
            ],
            options={
                'verbose_name_plural': 'Webiner Pioneers',
                'db_table': 'jinoe_webiner_pioneers',
            },
        ),
    ]
