# Generated by Django 4.0.6 on 2022-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinerpioneers',
            name='pioneer_category',
            field=models.CharField(choices=[('HST', 'Hoster'), ('PRS', 'Presenter'), ('CH', 'Cohost')], default='HST', max_length=30),
        ),
    ]
