# Generated by Django 4.0.6 on 2022-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_webinerpioneers_pioneer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinerpioneers',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='webinerupdates',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
